//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectionAgency.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debt_Client
    {
        public int ID_Debt_Client { get; set; }
        public int Debt_ID { get; set; }
        public int Client_ID { get; set; }
        public int Debt_Finish_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Debt Debt { get; set; }
        public virtual Debt_Finish Debt_Finish { get; set; }
    }
}
